// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    //...
    "aws_appsync_authenticationType": "AWS_IAM",
    //...
};


export default awsmobile;
